import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  const currentYear = new Date().getFullYear();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen">
      <header className="bg-gray-800 text-white px-4 py-2">
        <h1 className="text-lg font-bold">My Website</h1>
      </header>
      <main className="flex-1 p-4">
        <h2 className="text-xl font-bold mb-4">Welcome to my website!</h2>
        <p className="text-gray-600">
          <Link href="/posts/first-post">First post</Link>
        </p>
      </main>
      <footer className="bg-gray-800 text-white px-4 py-2">
        <p className="text-center">Copyright © {currentYear}</p>
      </footer>
      </main>
    </>
  )
}
