import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <ul>
          <li>
            <Link href="/posts/first-post">First post</Link>
          </li>
        </ul>
        <Image
          src="/next.svg"
          alt=""
          width={1000}
          height={1000}
        />
      </main>
    </>
  )
}
