name: Build Next.js

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn export
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./out/*
          key: ${{ github.sha }}