name: Build Next.js

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable
      - run: yarn build
      - run: yarn export
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./out/*
          key: ${{ github.sha }}