name: Rebuild site when Dynamic content is Published

on:
  repository_dispatch:
    types: [sanity_webhook_trigger]

jobs:
  received:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

