name: Rebuild site when Dynamic content is Published

on:
  repository_dispatch:
    types: [sanity_webhook_trigger]

jobs:
  received:
    runs-on: ubuntu-latest
    steps:
     - name: Debug initiator
       run: |
          echo "By: ${{ github.triggering_actor }}"
          echo "From: ${{ github.event.client_payload.initiatedFrom }}"
          echo "What: ${{ github.event.action }}"
  rebuild:
    uses: ./.github/workflows/deploy.yml

