name: Rebuild site when Dynamic content is Published

on:
  repository_dispatch:
    types: [sanity_webhook_trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm received
        run: echo "Received from Sanity.io!"
